
SIZE_WINDOW_X = 360
SIZE_WINDOW_Y = 640

DEFAULT_LIFE_BEE = 3
DEFAULT_PTS_BEE = 0

N_TICKS = 30

POSITION_Y_BG2 = -640

POSITION_Y_SPIDER = -50

POSITION_Y_FLOWER = 200

INITIAL_POSITION_BEE_X = 150
INITIAL_POSITION_BEE_Y = 600

SIZE_TEXT_SCORE = 120
INIT_TEXT_SCORE = "0"
SIZE_TEXT_LIFES = 60
INIT_TEXT_LIFES = "3"

POSITION_TEXT_SCORE_X = 160
POSITION_TEXT_SCORE_Y = 50

POSITION_TEXT_LIFES_X = 50
POSITION_TEXT_LIFES_Y = 50

TAX_UPDATE_Y_BG = 10
TAX_UPDATE_Y_BG2 = 10

POS_INITIAL_Y_BG = 640
POS_INITIAL_Y_BG2 = -640

N_TICKS_SPIDER = 8
N_SPRITES_SPIDER = 5

N_TICKS_FLOWER = 8
N_SPRITES_FLOWER = 3

N_TICKS_BEE = 2
N_SPRITES_BEE = 5

TAX_UPDATE_Y_SPIDER = 11
LIM_Y_SPIDER = 640

TAX_UPDATE_Y_FLOWER = 8
LIM_Y_FLOWER = 640
INITIAL_POSITION_FLOWER_Y = -100

SHIFT_X_MOUSE = -35
SHIFT_Y_MOUSE = -30

COLOR = (255, 255, 255)

INIT_X = 0
INIT_Y = 0
